/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package n43_aplicacionescritorio;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Animal;
import model.Persona;
import model.PersonaDAO;

/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    ArrayList <Animal> listaAnimales = new ArrayList <Animal>();
    int i = 0;
    String accion;
    
    public Vista() {
        initComponents();
        
        leerDatos();
        refrescar(0);

        activarFlechasAlante(true);
        activarFlechasAtras(false);

        this.btn_guardar.setEnabled(false);
        this.btn_cancelar.setEnabled(false);

        this.error_nombre.setVisible(false);
        this.error_edad.setVisible(false);

        
    }


    public void vaciarCampos() {
        this.tf_nombre.setText("");
        this.tf_edad.setText("");
        this.tf_id.setText("");
        this.tf_indice.setText("");

        this.tf_nombre.setEditable(true);
        this.tf_edad.setEditable(true);
    }

    public void refrescar(int i) {
        this.tf_nombre.setText(listaAnimales.get(i).getNombre());
        this.tf_edad.setText(String.valueOf(listaAnimales.get(i).getEdad()));
        this.tf_indice.setText(String.valueOf(i));

        //i = 0;
    }

    public void activarFlechasAlante(boolean ac) {
        this.btn_posterior.setEnabled(ac);
        this.btn_ultimo.setEnabled(ac);
    }

    public void activarFlechasAtras(boolean ac) {
        this.btn_anterior.setEnabled(ac);
        this.btn_primero.setEnabled(ac);
    }
    
    public void activarBotonesCentrales(boolean ac) {
        this.btn_insertar.setEnabled(ac);
        this.btn_eliminar.setEnabled(ac);
        this.btn_modificar.setEnabled(ac);
    }
    
    public void activarBotonesSuperiores(boolean ac) {
        this.btn_guardar.setEnabled(ac);
        this.btn_cancelar.setEnabled(ac);
    }
    
    public void activarDesactivarFlechas() {
        if (i == listaAnimales.size() - 1) {
            activarFlechasAlante(false);
            activarFlechasAtras(true);
        } else if (i == 0) {
            activarFlechasAlante(true);
            activarFlechasAtras(false);
        } else {
            activarFlechasAlante(true);
            activarFlechasAtras(true);
        }
    }
    
    // lee del fichero de texto ficheroEscirbirAnimal.txt
    private void leerDatos() {
        try {
            // indico donde esta el fichero (ruta) (2ª lin)
            // Pasar los datos a un buffer para leerlo desde la memoria ram (2ª lin)
            FileReader fichero = new FileReader("C:\\Users\\Usuario\\Desktop\\ADRIAN\\INFORMATICA\\DAW2\\SerjioJava\\ficheroEscribirAnimal.txt");
            BufferedReader datos = new BufferedReader(fichero);
            
            String linea = datos.readLine();
            while(linea != null) {
                Animal miAnimal = new Animal();
                String fila[] = linea.split(":");
                miAnimal.setNombre(fila[0]);
                miAnimal.setEdad(Integer.valueOf(fila[1]));
                listaAnimales.add(miAnimal);
                linea = datos.readLine();
            }
            //this.TextArea.setText(texto);
            datos.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    // Escribe en el fichero de texto ficheroEscirbirAnimal.txt
    private void escribirDatos() {
        try {
            FileWriter ficheroEscribir = new FileWriter("C:\\Users\\Usuario\\Desktop\\ADRIAN\\INFORMATICA\\DAW2\\SerjioJava\\ficheroEscribirAnimal.txt");
            BufferedWriter datosEscribir = new BufferedWriter(ficheroEscribir);
            // recorrer ArrayList
            // escribir en fichero
            for(Animal miAnimal:listaAnimales) {
                datosEscribir.write(miAnimal.toString());
                datosEscribir.newLine();
            }
            datosEscribir.close();
            //JOptionPane.showMessageDialog(null,"Guardado correctamente");
        } catch (IOException ex) {
            //JOptionPane.showMessageDialog(null,ex);
            JOptionPane.showMessageDialog(null,"Error al guardar");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JpAnimal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_primero = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_posterior = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        tf_indice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_insertar = new javax.swing.JButton();
        error_nombre = new javax.swing.JLabel();
        error_edad = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpAnimal.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar persona"));

        jLabel1.setText("nombre:");
        jLabel1.setToolTipText("Introduce el nombre");

        tf_nombre.setEditable(false);
        tf_nombre.setToolTipText("Debes de introducir un nombre");

        jLabel3.setText("edad");

        tf_edad.setEditable(false);

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel4.setText("id");

        tf_id.setEditable(false);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setText("modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/primer.png"))); // NOI18N
        btn_primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeroActionPerformed(evt);
            }
        });

        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enrere.png"))); // NOI18N
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_posterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/endavant.png"))); // NOI18N
        btn_posterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posteriorActionPerformed(evt);
            }
        });

        btn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ultim.png"))); // NOI18N
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        tf_indice.setEditable(false);
        tf_indice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_indiceActionPerformed(evt);
            }
        });

        jLabel5.setText("Indice:");

        btn_insertar.setText("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        error_nombre.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_nombre.setForeground(new java.awt.Color(255, 51, 51));
        error_nombre.setText("Debes de introducir un nombre");

        error_edad.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_edad.setForeground(new java.awt.Color(255, 0, 51));
        error_edad.setText("Debes de introducir una edad");
        error_edad.setToolTipText("");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpAnimalLayout = new javax.swing.GroupLayout(JpAnimal);
        JpAnimal.setLayout(JpAnimalLayout);
        JpAnimalLayout.setHorizontalGroup(
            JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAnimalLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(tf_indice, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpAnimalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_primero)
                .addGap(18, 18, 18)
                .addComponent(btn_anterior)
                .addGap(38, 38, 38)
                .addComponent(btn_posterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ultimo)
                .addGap(179, 179, 179))
            .addGroup(JpAnimalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpAnimalLayout.createSequentialGroup()
                        .addComponent(btn_insertar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JpAnimalLayout.createSequentialGroup()
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JpAnimalLayout.createSequentialGroup()
                                .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JpAnimalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(error_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        JpAnimalLayout.setVerticalGroup(
            JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAnimalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpAnimalLayout.createSequentialGroup()
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(error_nombre))
                        .addGap(18, 18, 18)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(error_edad))
                        .addGap(74, 74, 74)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_insertar)
                            .addComponent(btn_modificar)
                            .addComponent(btn_eliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ultimo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_posterior, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_anterior, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_primero, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addGroup(JpAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22))
                    .addGroup(JpAnimalLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btn_guardar)
                        .addGap(3, 3, 3)
                        .addComponent(btn_cancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_salir))
                    .addComponent(JpAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // ocultar errores
        this.error_nombre.setVisible(false);
        this.error_edad.setVisible(false);

        // que no haya campos vacios
        if (this.tf_nombre.getText().equals("") || this.tf_edad.getText().equals("")) {
            if (tf_nombre.getText().equals("")) {
                this.error_nombre.setVisible(true);
            }
            
            if (this.tf_edad.getText().equals("")) {
                this.error_edad.setVisible(true);
            }
        } else {
            // insertar
            if (accion.equals("insertar")) {
                // crear una persona
                Animal animal = new Animal();

                // recuperar a la persona de los jtextfild
                String nombre = this.tf_nombre.getText();
                int edad = 0;
                boolean pasa = true;
                try {
                    edad = Integer.valueOf(this.tf_edad.getText());
                } catch (Exception e) {
                    while (pasa) {
                        JOptionPane.showMessageDialog(null, "No estas introduciendo un numero");
                        try {
                            edad = Integer.valueOf(JOptionPane.showInputDialog("Introduce la edad"));
                            pasa = false;
                        } catch (Exception ex) {
                            pasa = true;
                        }

                    }
                }

                // insertar a la persona
                animal.setNombre(nombre);
                animal.setEdad(edad);
                try {
                    // insertar animal en array
                    this.listaAnimales.add(animal);
                    // escribir array en el fichero
                    escribirDatos();
                    
                    // restaurar botones (menos le posterior y el ultimo)
                    this.btn_insertar.setEnabled(true);
                    this.btn_modificar.setEnabled(true);
                    this.btn_eliminar.setEnabled(true);
                    this.btn_guardar.setEnabled(false);

                    this.btn_primero.setEnabled(true);
                    //this.btn_posterior.setEnabled(true);
                    this.btn_anterior.setEnabled(true);
                    //this.btn_ultimo.setEnabled(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }

            } else if (accion.equals("modificar")) {
                // modificar persona
                Animal animal = new Animal();
                animal.setNombre(this.tf_nombre.getText());
                //int edad = 0;
                boolean pasa = true;
                try {
                    //edad = Integer.valueOf(this.tf_edad.getText());
                    animal.setEdad(Integer.valueOf(this.tf_edad.getText()));
                } catch (Exception e) {
                    while (pasa) {
                        JOptionPane.showMessageDialog(null, "No estas introduciendo un numero");
                        try {
                            //edad = Integer.valueOf(JOptionPane.showInputDialog("Introduce la edad"));
                            animal.setEdad(Integer.valueOf(JOptionPane.showInputDialog("Introduce la edad")));
                            pasa = false;
                        } catch (Exception ex) {
                            pasa = true;
                        }

                    }
                }
                try {
                    listaAnimales.get(0).setNombre("ss");
                    listaAnimales.set(i, animal);
                    // escribir array en el fichero
                    escribirDatos();
                    
                    JOptionPane.showMessageDialog(rootPane, "Persona modificada correctamente");

                    // restaurar botones (menos le posterior y el ultimo)
                    this.btn_insertar.setEnabled(true);
                    this.btn_modificar.setEnabled(true);
                    this.btn_eliminar.setEnabled(true);
                    this.btn_guardar.setEnabled(false);

                    this.btn_primero.setEnabled(true);
                    this.btn_posterior.setEnabled(true);
                    this.btn_anterior.setEnabled(true);
                    this.btn_ultimo.setEnabled(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }

            this.tf_nombre.setEditable(false);
            this.tf_edad.setEditable(false);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Estas seguro de que quieres eliminar este usuario", "Atencion", dialogButton);
        if (dialogResult == 0) {
            // Eliminar a la persona
            listaAnimales.remove(i);
            JOptionPane.showMessageDialog(null, "Persona eliminada");
            
            // escribir fichero
            escribirDatos();
            
            // ir al ultimo objeto de la lista
            i = listaAnimales.size() - 1;
            refrescar(i);
            
            activarDesactivarFlechas();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha eliminado");
        }


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        this.tf_nombre.setEditable(true);
        this.tf_edad.setEditable(true);

        this.btn_insertar.setEnabled(false);
        this.btn_modificar.setEnabled(false);
        this.btn_eliminar.setEnabled(false);
        this.btn_guardar.setEnabled(true);
        this.btn_cancelar.setEnabled(true);

        activarFlechasAlante(false);
        activarFlechasAtras(false);

        accion = "modificar";


    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        // boton anterior
        activarFlechasAlante(true);
        if (i == 1) {
            i = 0;
            activarFlechasAtras(false);
        } else {
            i = i - 1;
        }
        refrescar(i);
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        // boton ultimo
        i = listaAnimales.size() - 1;
        refrescar(i);

        activarFlechasAlante(false);
        activarFlechasAtras(true);
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_posteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posteriorActionPerformed
        // boton posterior
        activarFlechasAtras(true);
        if (i == listaAnimales.size() - 2) {
            i = listaAnimales.size() - 1;
            activarFlechasAlante(false);
        } else {
            i = i + 1;
        }
        refrescar(i);
    }//GEN-LAST:event_btn_posteriorActionPerformed

    private void btn_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeroActionPerformed
        i = 0;
        refrescar(i);
        
        //refrescar(0);
        activarFlechasAlante(true);
        activarFlechasAtras(false);
    }//GEN-LAST:event_btn_primeroActionPerformed

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
        this.btn_insertar.setEnabled(false);
        this.btn_modificar.setEnabled(false);
        this.btn_eliminar.setEnabled(false);
        this.btn_guardar.setEnabled(true);
        this.btn_cancelar.setEnabled(true);

        activarFlechasAlante(false);
        activarFlechasAtras(false);

        accion = "insertar";
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        activarDesactivarFlechas();
        
        refrescar(i);
        this.tf_nombre.setEditable(false);
        this.tf_edad.setEditable(false);

        this.error_nombre.setVisible(false);
        this.error_edad.setVisible(false);
        
        this.btn_insertar.setEnabled(true);
        this.btn_modificar.setEnabled(true);
        this.btn_eliminar.setEnabled(true);
        this.btn_guardar.setEnabled(false);
        this.btn_cancelar.setEnabled(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void tf_indiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_indiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_indiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpAnimal;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_posterior;
    private javax.swing.JButton btn_primero;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel error_edad;
    private javax.swing.JLabel error_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_indice;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
}
