/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package n43_aplicacionescritorio;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Medida;
import model.Persona;

/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    Medida medida = new Medida();

    public Vista() {
        initComponents();
        ocultarErrores();
    }

    public void vaciarCampos() {
        this.tf_celsius.setText("");
        this.tf_fahrenheit.setText("");
        this.tf_celsius.setEditable(true);
        this.tf_fahrenheit.setEditable(true);
    }
    
    public void llenarCampos() {
        this.tf_celsius.setText(medida.getCelsius());
        this.tf_fahrenheit.setText(medida.getFahrenheit());
        this.tf_celsius.setEditable(true);
        this.tf_fahrenheit.setEditable(true);
    }

    public void ocultarErrores() {
        this.error_celsius.setVisible(false);
        this.error_fahrenheit.setVisible(false);
        this.error_conversion.setVisible(false);
    }
    
    public Double tempVacia(String text) {
        boolean pasa = false;
        Double temp = 0.0;
        try {
            temp = Double.valueOf(text);
        } catch (Exception e) {
            while (!pasa) {
                JOptionPane.showMessageDialog(null, "No estas introduciendo un numero valido");
                try {
                    String resJO = JOptionPane.showInputDialog("Introduce la temperatura");
                    //if (resJO != null) {
                        temp = Double.valueOf(resJO);
                        pasa = true;
                    //} else {
                        pasa = true;
                    //}
                } catch (Exception ex) {
                    pasa = false;
                }
            }
        }
        return temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JpPersona = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_celsius = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        error_celsius = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_fahrenheit = new javax.swing.JTextField();
        error_fahrenheit = new javax.swing.JLabel();
        rb_CtoF = new javax.swing.JRadioButton();
        rb_FtoC = new javax.swing.JRadioButton();
        error_conversion = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpPersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar persona"));

        jLabel3.setText("Celsius");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        error_celsius.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_celsius.setForeground(new java.awt.Color(255, 0, 51));
        error_celsius.setText("Introduce una temperatura");
        error_celsius.setToolTipText("");

        jLabel4.setText("Fahrenheit");

        error_fahrenheit.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_fahrenheit.setForeground(new java.awt.Color(255, 0, 51));
        error_fahrenheit.setText("Introduce una temperatura");
        error_fahrenheit.setToolTipText("");

        buttonGroup1.add(rb_CtoF);
        rb_CtoF.setText("Celsius-Fahrenheit");
        rb_CtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_CtoFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_FtoC);
        rb_FtoC.setText("Fahrenheit-Celsius");

        error_conversion.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_conversion.setForeground(new java.awt.Color(255, 0, 51));
        error_conversion.setText("Selecciona una conversion");
        error_conversion.setToolTipText("");

        javax.swing.GroupLayout JpPersonaLayout = new javax.swing.GroupLayout(JpPersona);
        JpPersona.setLayout(JpPersonaLayout);
        JpPersonaLayout.setHorizontalGroup(
            JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPersonaLayout.createSequentialGroup()
                .addGroup(JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpPersonaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_celsius, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tf_fahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpPersonaLayout.createSequentialGroup()
                                .addGroup(JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpPersonaLayout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addGroup(JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_calcular)
                                            .addComponent(rb_CtoF)
                                            .addComponent(rb_FtoC)))
                                    .addComponent(error_celsius))
                                .addGap(18, 18, 18)
                                .addComponent(error_fahrenheit))))
                    .addGroup(JpPersonaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(error_conversion)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        JpPersonaLayout.setVerticalGroup(
            JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPersonaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error_celsius)
                    .addComponent(error_fahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_celsius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_fahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(error_conversion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_CtoF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_FtoC)
                .addGap(17, 17, 17)
                .addComponent(btn_calcular)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_salir))
                    .addComponent(JpPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // ocultar errores
        ocultarErrores();
        Double temperatura;
        
        if (this.rb_CtoF.isSelected() != true && this.rb_FtoC.isSelected() != true) {
            this.error_conversion.setVisible(true);
        } else {
            if (this.rb_CtoF.isSelected() == true) {
                //JOptionPane.showMessageDialog(rootPane, "c to f");
                if (tf_celsius.getText().equals("")) {
                    this.error_celsius.setVisible(true);
                } else {
                    temperatura = tempVacia(this.tf_celsius.getText());
                    String res = medida.calularMedida("fahrenheit", temperatura);
                    medida.setFahrenheit(res);
                    medida.setCelsius(this.tf_celsius.getText());
                } 
            }

            if (this.rb_FtoC.isSelected() == true) {
                //JOptionPane.showMessageDialog(rootPane, "f to c");
                if (tf_fahrenheit.getText().equals("")) {
                    this.error_fahrenheit.setVisible(true);
                } else {
                    temperatura = tempVacia(this.tf_fahrenheit.getText());
                    String res = medida.calularMedida("celsius", temperatura);
                    medida.setCelsius(res);
                    medida.setFahrenheit(this.tf_fahrenheit.getText());
                }
            }

            llenarCampos();
        }
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void rb_CtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_CtoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_CtoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpPersona;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel error_celsius;
    private javax.swing.JLabel error_conversion;
    private javax.swing.JLabel error_fahrenheit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rb_CtoF;
    private javax.swing.JRadioButton rb_FtoC;
    private javax.swing.JTextField tf_celsius;
    private javax.swing.JTextField tf_fahrenheit;
    // End of variables declaration//GEN-END:variables
}
